### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## User info
#username: 

## aur info
paru:
  git_url: https://aur.archlinux.org/paru.git
  install_dir: /usr/bin/paru
  build_dir: ~/paru
  install_shell: makepkg -si --noconfirm

yay:
  git_url: https://aur.archlinux.org/yay.git
  install_dir: /usr/bin/yay
  build_dir: ~/yay
  install_shell: makepkg -si --noconfirm

## paru pkg install
aur:
#  packages:
#    - obmenu
#    - obmenu-generator
#    - nitrogen
  pkg_install_shell: paru -S --noconfirm obmenu obmenu-generator nitrogen

## zplug info
zplug:
  git_url: https://github.com/zplug/zplug
  install_dir: ~/.zplug

## Task Configuration
setup_zsh: True

## Dotfiles
## Please make sure to update 
pull_dotfiles: True

dotfiles:
    url: https://github.com/Nka700/.dotfiles.git
    destination: work/dotfiles
    rcup_flags: -fx README.md

## Desktop
install_openbox: True

## App Preferences
## ===========================
# Web Browser
# Value can be: vivaldi, firefox, brave, or chromium
browser: chromium

## When set to True, will install elinks and w3m
install_terminal_browsers: True

## Installs LibreOffice Fresh when True
install_office: True

## Console-based email client
install_aerc: True

## AUR vars
use_aur: True

## python packages
python:
  packages:
    - pynvim

## Installs python packages
install_pythonpkg: True
