### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## User info
username: nka700

## aur info
paru:
  git_url: https://github.com/Morganamilo/paru.git
  install_dir: ~/paru
  install_shell: makepkg -si

## zplug info
zplug:
  git_url: https://github.com/zplug/zplug
  install_dir: ~/.zplug

## Task Configuration
setup_zsh: True

## Dotfiles
## Please make sure to update 
pull_dotfiles: True

dotfiles:
    url: https://github.com/linuxpiper/dotfiles.git
    destination: projects/dotfiles
    rcup_flags: -fx README.md

## Desktop
install_openbox: True

## App Preferences
## ===========================
# Web Browser
# Value can be: vivaldi, firefox, brave, or chromium
browser: chromium

## When set to True, will install elinks and w3m
install_terminal_browsers: True

## Installs LibreOffice Fresh when True
install_office: True

## Console-based email client
install_aerc: True

### AUR vars
### ===========================
use_aur: True
#
#aur:
#    dir: aur
#    packages:
#        - paru
#        - downgrade
##        - zplug
#        - miller
#        - myrepos
#        - ctmg
#        - spiped
### ===========================

