#- name: Stat paru
#  become: yes
#  become_user: '{{ username }}'
#  stat:
#    path: "{{ paru.install_dir }}"
#  register: paru_dir
#
#- name: Install paru for users_1
#  become: yes
#  become_user: '{{ username }}'
#  git:
#    repo: "{{ paru.git_url }}"
#    dest: "{{ paru.build_dir }}"
#  when: not paru_dir.stat.exists
#
#- name: Install paru for users_2
#  become: yes
#  become_user: '{{ username }}'
#  shell: "{{ paru.install_shell }}"
#  args:
#    chdir: "{{ paru.build_dir }}"
#  when: not paru_dir.stat.exists

#- name: Install aur pkg for users
#  become: yes
#  become_user: '{{ username }}'
#  shell: "{{ paru.pkg_install_shell }}"
#  ignore_errors: yes

- name: Stat yay
  become: yes
  become_user: '{{ username }}'
  stat:
    path: "{{ yay.install_dir }}"
  register: yay_dir

- name: Install yay for users_1
  become: yes
  become_user: '{{ username }}'
  git:
    repo: "{{ yay.git_url }}"
    dest: "{{ yay.build_dir }}"
  when: not yay_dir.stat.exists

- name: Install yay for users_2
  become: yes
  become_user: '{{ username }}'
  shell: "{{ yay.install_shell }}"
  args:
    chdir: "{{ yay.build_dir }}"
  when: not yay_dir.stat.exists

#- name: Install aur pkg for users
#  become: yes
#  become_user: '{{ username }}'
#  shell: "{{ yay.pkg_install_shell }}"
#  ignore_errors: yes
