- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - archlinux-keyring
    - acpi
    - acpilight
    - bind
    - strace
    - sysstat
    - jgmenu
    - base-devel
    - htop
    - kitty
    - libva
    - libva-intel-driver
    - libva-utils
    - network-manager-applet
    - networkmanager
    - networkmanager-openvpn
    - openssh
    - picom
    - python-setuptools
    - source-highlight
    - tint2
    - tree
    - vi
    - wpa_supplicant
    - xfce4-power-manager
    - xfce4-terminal
    - xorg-xinput
    - xorg-xwininfo
    - xorg-xdpyinfo
   state: latest
   update_cache: yes

- name: Install archival utils
  pacman:
    name:
#      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
#      - aria2
      - curl
      - wget
      - flatpak
      - python-pip
    state: present

- name: Install extra packages
  pacman:
    name:
      - arch-audit-gtk
      - bashtop
      - blueman
      - bluez
      - conky
      - docker
      - docker-compose
      - evince
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-mozc
      - fcitx5-qt
      - gimp
      - git
      - go
      - gsimplecal
      - gsimplecal
      - jq
      - lshw
      - mpv
      - noto-fonts-cjk
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-emoji
      - nvidia
      - nvidia-settings
      - nvidia-utils
      - pamixer
      - pavucontrol
      - pulseaudio
      - pulseaudio-bluetooth
      - redshift
      - rofi
      - slock
      - vlc
      - whois
      - wireguard-tools
      - xf86-video-nouveau
#      - gvim
#      - nvidia-dkms
    state: present

- name: Install python packages
  pip:
    name:
      - pynvim
    state: present

- name: enable sshd
  systemd:
    name: sshd.service
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes

- name: enable docker
  systemd:
    name: docker.service
    daemon_reload: yes
    enabled: yes
  become: yes

