- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - kitty
    - vi
    - source-highlight
    - tree
    - base-devel
    - openssh
    - xfce4-terminal
    - xfce4-power-manager
    - wpa_supplicant
    - tint2
    - networkmanager
    - networkmanager-openvpn
    - network-manager-applet
    - archlinux-keyring
    - htop
    - picom
   state: latest
   update_cache: yes

- name: Install archival utils
  pacman:
    name:
#      - atool
#      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
#      - aria2
      - curl
      - wget
      - flatpak
      - python-pip
    state: present

- name: Install extra packages
  pacman:
    name:
      - arch-audit-gtk
      - conky
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-mozc
      - fcitx5-qt
      - vlc
      - mpv
      - gimp
      - git
      - gvim
      - gsimplecal
      - jq
      - blueman
      - bluez
      - pulseaudio
      - pulseaudio-bluetooth
      - pavucontrol
      - slock
      - noto-fonts-cjk
      - noto-fonts-emoji
      - docker
      - docker-compose
      - lshw
      - rofi
      - redshift
      - noto-fonts-cjk
      - noto-fonts-emoji
      - nvidia
      - nvidia-dkms
      - nvidia-settings
      - nvidia-utils
      - xf86-video-nouveau
      - gsimplecal
    state: present

- name: Install python packages
  pip:
    name:
      - pynvim
    state: present

- name: enable sshd
  systemd:
    name: sshd.service
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes

- name: enable docker
  systemd:
    name: docker.service
    daemon_reload: yes
    enabled: yes
  become: yes

