- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - kitty
    - vlc
    - gimp
    - git
    - vim
    - vi
    - source-highlight
    - tree
    - base-devel
    - openssh
    - xfce4-terminal
    - wpa_supplicant
    - blueman
    - bluez
    - pulseaudio-bluetooth
    - tint2
    - networkmanager
    - networkmanager-openvpn
    - archlinux-keyring
    - htop
   state: present

- name: Install archival utils
  pacman:
    name:
#      - atool
#      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
#      - aria2
      - curl
      - wget
      - flatpak
      - python-pip
    state: present

- name: Install extra packages
  pacman:
    name:
      - noto-fonts-cjk
      - noto-fonts-emoji
      - docker
      - docker-compose
    state: present

- name: Install python packages
  pip:
    name:
      - pynvim
    state: present

- name: enable sshd
  systemd:
    name: sshd.service
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes

