- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - kitty
    - vlc
    - gimp
    - git
#    - thefuck
#    - tmux
#    - lsd
    - vim
    - vi
    - source-highlight
    - tree
    - base-devel
    - openssh
   state: present

- name: Install archival utils
  pacman:
    name:
      - atool
#      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
      - wpa_supplicant
    state: present

- name: Install download utils
  pacman:
    name:
#      - aria2
      - curl
      - wget
    state: present

- name: enable sshd
  systemd:
    name: sshd.service
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes

