- name: mkdir for openbox dotfiles
  file:
    path: ~/.config/openbox
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ username }}"

#- name: Clone user dotfiles
#  git: repo={{ dotfiles.url }} dest=/home/{{ username }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
#  become: yes
#  become_user: "{{ username }}"
#
#- name: Install user dotfiles
#  command: rcup -d /home/{{ username}}/{{ dotfiles.destination}} {{ dotfiles.rcup_flags }}
#  become: yes
#  become_user: "{{ username }}" 
