- name: mkdir for openbox dotfiles
  file:
    path: ~/.config/openbox
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ username }}"

- name: Clone user dotfiles
  git: 
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles.destination }}"
#    accept_hostkey: yes 
    update: no
  become: yes
  become_user: "{{ username }}"

- name: Install user dotfiles
  command: rcup "{{ dotfiles.rcup_flags }}"
  become: yes
  become_user: "{{ username }}" 

- name: link conkyrc1 
  file:
    src: "{{ dotfiles.destination }}"/cofig/conky/conkyrc
    dest: ~/.config/conky/.conkyrc
    state: link
  become: yes
  become_user: "{{ username }}"

- name: link conkyrc2 
  file:
    src: "{{ dotfiles.destination }}"/cofig/conky/conkyrc2
    dest: ~/.config/conky/.conkyrc2
    state: link
  become: yes
  become_user: "{{ username }}"

