- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes

# Install and configure zsh
- include_tasks: user.yml

# Configure pacman (colorize and repos)
- include_tasks: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include_tasks: core-apps.yml

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# Install openbox 
- include_tasks: openbox.yml
  when: install_openbox == True

# Web Browser
- include_tasks: "{{browser}}.yml"

# Terminal web browsers
- include_tasks: terminal_browsers.yml
  when: install_terminal_browsers == True

## AUR apps
- include_tasks: aur.yml
  when: use_aur == True

    
## python apps
- include_tasks: pythonpkg.yml
  when: install_pythonpkg == True
#
## Dotfiles
#- include_tasks: dotfiles.yml
#  when: pull_dotfiles == True
