- name: install openbox
  community.general.pacman:
    name: 
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - openbox
      - xfce4-settings
    state: present 
  become: yes

- name: enable lightdm
  systemd:
    name: lightdm.service
#    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

