---

- name: add "{{ username }}" user
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ upassword | password_hash('sha512') }}"
    append: yes
    groups:
      - wheel

- hosts: localhost
  become: True
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^#%wheel ALL=(ALL) ALL'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
