---

- name: install zsh
  community.general.pacman:
   name: 
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
   state: present

#- name: install fzf for zsh
#  community.general.pacman:
#   name: 
#    - fzf
#   state: present

- name: change "{{ username }}" shell to zsh
  become: yes
  user:
   name: "{{ username }}"
   groups:
     - wheel
   shell: /usr/bin/zsh

- name: Install zplug for users
  become: yes
  become_user: '{{ username }}'

- name: Stat zplug
  stat:
    path: "{{ zplug.install_dir }}"
  register: zplug_dir

- name: Install zplug for users
  become: yes
  become_user: '{{ username }}'
  git:
    repo: "{{ zplug.git_url }}"
    dest: "{{ zplug.install_dir }}"
  when: not zplug_dir.stat.exists

#- name: copy zsh dotfile
#  copy: 
#   src: user_home/.zshrc 
#   dest: /home/{{ username }}/.zshrc
#   force: False
#   owner: "{{ username }}"
#   group: "{{ username }}"
#   mode: u+rw,g+r,o--

#- name: copy zsh p10k dotfile
#  copy: 
#   src: user_home/.p10k.zsh
#   dest: /home/{{ username }}/.p10k.zsh
#   force: False
#   owner: "{{ username }}"
#   group: "{{ username }}"
#   mode: u+rw,g+r,o--

#- name: copy powerlevel10k theme
#  copy:
#   src: zsh-theme-powerlevel10k/
#   dest: /usr/share/zsh-theme-powerlevel10k/
#   force: False
#   mode: u+rw,g+xr,o+x

